[package]
name = "sqlite-extractor"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.53"
env_logger = "0.9.0"
log = "0.4.14"
tokio = { version = "1.16.1", features = ["rt-multi-thread", "fs", "macros", "io-util"] }

[dev-dependencies]
sha2 = "0.10.1"
